#!/usr/bin/env node
// file-map - render "what every shipped file is, and why" from the manifest.
//
// The question this answers - "what is this folder, what goes in it, why does it exist" - had
// two half-answers: a per-folder README convention that the tree does not fully hold, and
// nothing at all for a reader who wants the whole map in one place.
//
// It is GENERATED rather than authored, and that is the entire point. `standard.manifest.json`
// already carries a purpose, an adapt class, a profile and the rule it enforces for all of it -
// self-verify reads exactly this data to decide compliance. A hand-written map would be a
// second description of the same thing, and this repo has spent a lot of effort on what happens
// to second descriptions.
//
// Usage:
//   node tools/file-map.mjs           # write docs/file-map.md
//   node tools/file-map.mjs --check   # exit 1 if the written file is stale (CI)
//
// Zone 1 tooling - never shipped. No dependencies.

import { readFileSync, writeFileSync, existsSync } from "node:fs";

const OUT = "docs/file-map.md";
const check = process.argv.includes("--check");
const m = JSON.parse(readFileSync("standard/standard.manifest.json", "utf8"));

const SPEC = "../standard/SPEC.md";
// Top-level grouping, in the order a reader meets them rather than alphabetically: the entry
// files first, then what they point at.
const ORDER = ["(root)", "docs", "specs", "scripts", ".claude", ".github"];
const HEADING = {
  "(root)": "At the root - what an agent and a reader meet first",
  docs: "`docs/` - the knowledge the repo keeps",
  specs: "`specs/` - behaviour, by capability",
  scripts: "`scripts/` - the guards, and the spec engine's runtime",
  ".claude": "`.claude/` - the procedures, in Claude Code's reference form",
  ".github": "`.github/` - templates, never enabled in this repo",
};

const groupOf = (p) => (p.includes("/") ? p.split("/")[0] : "(root)");
const esc = (s) => String(s).replace(/\|/g, "\\|");

const rows = (entries) =>
  entries
    .map((e) => {
      const need = e.required ? "**required**" : "optional";
      const profile = e.profile === "scale" ? "scale" : "core";
      const rule = e.rule ? `[${e.rule}](${SPEC})` : "-";
      const alt = e.altPaths?.length ? ` <br><small>or ${e.altPaths.map((a) => `\`${a}\``).join(", ")}</small>` : "";
      return `| \`${e.path}\`${alt} | ${esc(e.purpose)} | ${need}, ${profile} | \`${e.adapt}\` | ${rule} |`;
    })
    .join("\n");

const groups = ORDER.filter((g) => m.files.some((f) => groupOf(f.path) === g)).map((g) => {
  const entries = m.files.filter((f) => groupOf(f.path) === g);
  return `## ${HEADING[g] ?? `\`${g}/\``}\n\n| Path | What it is, and why | Needed | Adapt | Rule |\n|---|---|---|---|---|\n${rows(entries)}`;
});

const refs = (m.references ?? [])
  .map((r) => `| [\`${r.path}\`](${r.url ?? "#"}) | ${esc(r.purpose ?? "")} |`)
  .join("\n");

const sections = (m.sections ?? [])
  .map((s) => `| \`${s.file}\` | \`${s.heading}\` | ${esc(s.purpose ?? "")} |`)
  .join("\n");

const body = `# What every shipped file is, and why

<!-- GENERATED by tools/file-map.mjs from standard/standard.manifest.json - do not edit by hand.
     Run \`node tools/file-map.mjs\` after changing the manifest; CI fails on a stale copy. -->

> **Generated, not written.** Every row below comes from
> [\`standard.manifest.json\`](../standard/standard.manifest.json) - the same data
> \`self-verify\` reads to decide whether your repo complies. A hand-written map would be a
> second description of the same thing, and second descriptions rot.

Read this when you are orienting: *what is this folder, why does it exist, which rule made it
so.* The **Rule** column links the numbered rule in the spec that each entry enforces, so any
row can be traced from "there is a file here" to "here is why the standard says so".

**Adapt** is how an entry lands in your repo when you align: \`copy\` arrives verbatim,
\`merge\` is reconciled with what you already have, and \`fill-from-repo\` is a shell you
author, because the standard never invents your content. **Needed** says whether a missing
entry counts as drift, and at which profile (\`core\` is every repo; \`scale\` is teams).

What this map does **not** tell you is *how to author* what goes inside a folder. Where that
needs a manual, the folder carries one as its own \`README.md\` and it appears as a row below,
so this map lists it rather than repeating it. Everywhere else the rule is a numbered rule in
the spec or a line in \`docs/conventions.md\` and the folder carries no README at all: a second
copy of a rule is a second thing to keep true.

${groups.join("\n\n")}

## Adopted by reference, never copied

These are not in your repo. They are read at their home in the standard, always latest
(ADR-023, ADR-025) - so the method improves without a re-scaffold, and \`self-verify\` notes
them rather than checking files.

| Document | What it covers |
|---|---|
${refs}

## Required headings

A file can exist and still be a shell. These headings are checked by name.

| File | Heading | Why it must be there |
|---|---|---|
${sections}
`;

if (check) {
  if (!existsSync(OUT)) {
    console.error(`file-map: ${OUT} does not exist - run \`node tools/file-map.mjs\``);
    process.exit(1);
  }
  if (readFileSync(OUT, "utf8") !== body) {
    console.error(`file-map: ${OUT} is stale - the manifest moved and the map did not.`);
    console.error("file-map: run `node tools/file-map.mjs` and commit the result.");
    process.exit(1);
  }
  console.log(`file-map: OK - ${OUT} matches the manifest (${m.files.length} entries)`);
  process.exit(0);
}

writeFileSync(OUT, body);
console.log(`file-map: wrote ${OUT} - ${m.files.length} entries, ${(m.references ?? []).length} references`);
